#!/bin/bash
# todo.txt add-on to create log of events
# Copyright (c) Lal Thomas, http://lalamboori.blogspot.in
# License: GPL3, http://www.gnu.org/copyleft/gpl.html

# Stop Verbose lines, thanks to Mark Harrison
TODOTXT_VERBOSE=0
TODOTXT_PLAIN=0

if [[ -z $LOG_FILE ]]; then
    LOG_FILE=log.txt
fi

function usage() {
    echo "  $(basename $0) [OPTION] "    
	echo "    OPTION"
	echo "    add <log entry> - add the log item (default)"
	echo "    usage - show the usage"
    exit
}

log(){	
	echo "$(date "+%Y-%m-%d %H%M%S") $@">> $doLogPath
}

# Get action
shift
action=$1
shift
# Get rest of them
entry="$@"

case "$action" in
	"usage")
		usage
		exit
		;;
	"add")
		log $entry
		exit
		;;	
	*)	
		log $action $entry
		exit
		;;	   
esac
